[package]
name = "renfs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "renfs"
path = "src/main.rs"
required-features = ["cli"]

[dev-dependencies]
examplify = "0.3"
tempfile = "3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
anyhow = { version = "1", optional = true }
async-fs = "2.2"
base64 = { version = "0.23", optional = true }
clap = { version = "4", features = ["derive"], optional = true }
dirs = "7"
flate2 = { version = "1", optional = true }
futures-lite = "2"
regex = { version = "1", optional = true }
tempfile = { version = "3", optional = true }
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"], optional = true }
ureq = { version = "3", optional = true }
url = { version = "2", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[features]
default = ["cli"]
cli = [
  "dep:anyhow",
  "dep:base64",
  "dep:clap",
  "dep:flate2",
  "dep:regex",
  "dep:tempfile",
  "dep:tracing",
  "dep:tracing-subscriber",
  "dep:ureq",
  "dep:url",
]
