[build]
target = "examples/index.html"
dist = "examples/bin/dist"
example = "simple"

[[hooks]]
stage = "pre_build"
command = "renfs"
command_arguments = ["examples/bin/zenfs.js", "--module", "dom"]

[watch]
ignore = ["examples/bin"]
