[package]
name = "webfs"
version = "0.1.0"
edition = "2024"
description = "A std::fs-like filesystem for localStorage"
readme = "README.md"
license = "MIT"

[target.'cfg(target_arch = "wasm32")'.dependencies]
base64 = "0.22"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Storage", "Window"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[dev-dependencies]
examplify = "0.3.0"
