on:
  push:
    branches: ["master"]
    tags:
      - "v*"
  pull_request:
    branches: ["master"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - uses: Swatinem/rust-cache@v2
      - run: mise check
  test-native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - uses: Swatinem/rust-cache@v2
      - run: mise test:native
  test-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - uses: Swatinem/rust-cache@v2
      - run: mise test:wasm
  create-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test-native, test-wasm]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: taiki-e/create-gh-release-action@v1
  release:
    name: release (${{ matrix.target }})
    if: startsWith(github.ref, 'refs/tags/v')
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
            build_tool: cargo
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
            build_tool: cargo
          - target: x86_64-unknown-linux-musl
            os: ubuntu-24.04
            build_tool: cross
          - target: aarch64-unknown-linux-musl
            os: ubuntu-24.04
            build_tool: cross
          - target: armv7-unknown-linux-gnueabihf
            os: ubuntu-24.04
            build_tool: cross
          - target: i686-unknown-linux-gnu
            os: ubuntu-24.04
            build_tool: cross
          - target: x86_64-unknown-freebsd
            os: ubuntu-24.04
            build_tool: cross
          - target: x86_64-pc-windows-msvc
            os: windows-2025
            build_tool: cargo
          - target: aarch64-pc-windows-msvc
            os: windows-11-arm
            build_tool: cargo
          - target: i686-pc-windows-msvc
            os: windows-2025
            build_tool: cargo
          - target: x86_64-apple-darwin
            os: macos-15-intel
            build_tool: cargo
          - target: aarch64-apple-darwin
            os: macos-15
            build_tool: cargo
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: renfs
          target: ${{ matrix.target }}
          build-tool: ${{ matrix.build_tool }}
          include: LICENSE,README.md
          checksum: sha256
          locked: true
